### PR TITLE
removing picard.jar and htsjdk.jar so we can clone or download them on

### PR DESCRIPTION
**Pull request by nh13**
demand using the clone-picard and download-picard ant targets
respectively.  The former clones the entire picard repository and checks
out the specific commit, and the latter downloads the specific commit
directly.  We also clone or download htsjdk as well

### CODE REVIEW

**Comment by nh13** [comment]
Right now picard and htsjdk clone/download the master commits, but this allows us to choose which commit we want to build off of, so that we don't break a build because htsjdk or picard has pushed changes to master that break our build.

**Comment by nh13** [comment]
@tfenne can you take a look.

**Comment by tfenne** [comment]
Looks fine I think.  My only real questions around around the `download-picard` task, and whether this couldn't instead by accomplished by first cloning picard if necessary, and then using git to navigate to the desired commit.  Mostly I'd be worried about accidentally over-writing my git checkout when using that.

**Comment by nh13** [comment]
There's the `clone-picard` task that does exactly this, but it may be good to have `download-picard` check if the directory already exists.

**Pull request merged**
