### PR TITLE
Nh adding some tools

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
@tfenne adding a few more tools and performed some code reorganization.  Please excuse the multiple features in one pull request here.

**Comment by tfenne** [comment]
@nh13 Didn't read in detail, but mostly looks fine to me.  Two questions:
1) How is RemapReadGroups different from Picard's AddOrReplaceReadGroups?
2) Was it not possible to extend Picard's CollectWgsMetrics vs. copying all the code over and modifying?

**Comment by nh13** [comment]
1. The purpose was if we wanted to have multiple (not just one) new read group.  The way it was implemented, if you set any of the attributes for the read group, they would be the same across the new read groups.  Now the tool simply accepts a file that maps from old read group id to new read group line, along with an option to keep the old attributes or not.
2. Some of the `CollectWgsMetrics` methods are not public (like the filters), and the main `doWork` method would need to be re-factored for this tool to work.  I did not feel it was worth the imposition on Picard to do that refactoring just for my tool.

**Comment by nh13** [comment]
@tfenne can I get a :+1:

**Comment by tfenne** [comment]
image

**Pull request merged**
